### ISSUE TITLE
Errors upgrading from Chef 11 -> 12 : ERROR: /cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.name' invalid"]}

### ISSUE THREAD

**Issue by jdpaton** [chef/opscode-omnibus#750] opened 2015-04-09 01:25 UTC
Any pointers on how to fix this? 

```
Updated /clients/jenkins-uploader.json
ERROR: /cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.name' invalid"]}
ERROR: LoadError: cannot load such file -- berkshelf/api/version
Failed uploading transformed data to the Chef 12 server
```

I've tried manually installing berkshelf using the embedded gem binary to no avail not sure if it's a red herring for the metadata.name issue?

command being run to reupload the transformed data:

```
chef-server-ctl chef12-upgrade-upload -e /tmp/chef12-server-data20150409-22088-ozok02/ -t 1
```

**Comment by mmzyk** [comment] 2015-04-09 01:54
@jdpaton Yeah, I think your instinct that it's a read hearing for the metadata.name issue. berkshelf shouldn't be needed for an upgrade at all.

What you're seeing is the same as this issue: https://github.com/chef/chef-server/issues/118

**Comment by mmzyk** [comment] 2015-04-09 01:56
I should have added that you're going to have to search for the offending cookbook, as right now the process doesn't give good errors in this case. Sorry about that. The upload should pick up where it left off however for any data that succeeded.

**Comment by mmzyk** [comment] 2015-04-10 01:19
I'm going to close this out since I believe this is a dupe of https://github.com/chef/chef-server/issues/118. If that isn't the case, feel free to reopen @jdpaton, or feel free to comment on that issue as well.

**Closed by mmzyk** 2015-04-10 01:19 UTC
